title: Chapitre

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          icone: 
            label: Icône
            type: files
          pics: 
            label: Images
            type: files
          summary: 
            label: Sommaire
            type: structure
            fields:
              title: 
                label: Titre de la partie
                type: text
          text: 
            label: Contenu
            type: blocks
            fieldsets:
              text: 
                label: Texte 
                type: group
                fieldsets:
                  - heading
                  - text
                  - list
                  - markdown
              quotes: 
                label: Citations 
                type: group
                fieldsets:
                  - quote
                  - verbatim
                  - sources
              media: 
                label: Media 
                type: group
                fieldsets:    
                  - gallery
                  - image
                  - spread
          sources:
            label: Sources
            type: list
          # text:
          #   label: Texte
          #   type: textarea
          #   size: huge
  sidebar:
    width: 1/3
    sections:
      # pages:
      #   type: pages
      #   template: default
      files:
        label: Fichiers / Images
        type: files

